-- Isolates Optuna's own tables (studies, trials, trial_params, ...) from
-- application tables in the same database — models/train/tuning.py's
-- RDBStorage connects with search_path=optuna, never 'public'.
-- Applied twice, deliberately: once here via docker-compose.yml's
-- docker-entrypoint-initdb.d mount (fresh containers only — that mount never
-- fires against an already-initialized data volume), and again explicitly by
-- tuning.py::_build_optuna_storage at call time, the same belt-and-braces
-- role utils/db.py::apply_migrations plays for the Alembic-managed tables, so a
-- pre-existing Postgres instance (CI's testcontainers, Phase 12's RDS, a
-- developer's already-initialized local container) still gets the schema.
-- This file stays outside this project's Alembic instance permanently
-- (PROJECT_PLAN.md's Phase 10a-i scope-boundary note).
CREATE SCHEMA IF NOT EXISTS optuna;
